spring:
   profiles:
      active: dev
   devtools:
      livereload:
         enabled: true
      restart:
         enabled: false
   http:
      encoding:
         charset: UTF-8
         enabled: true
         force: true
         force-request: true
         force-response: true
   aop:
      auto: true
   aop-proxy-target-class: true
mybatis:
   config-location: classpath:mybatis/configuration.xml
   
# 개발 환경
---
server:
   port: 8080
   context-path: /
spring:
   profiles: dev
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.1.218:3307/cafe24mall_test?allowMultiQueries=true
      username: cafe24mall
      password: cafe24mall
---

# 배포 환경
---
server:
   port: 8080
   context-path: /
spring:
   profiles: real
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.1.218:3307/cafe24mall?allowMultiQueries=true
      username: cafe24mall
      password: cafe24mall
---